name: Go package

on: [push]

env:
  app_name: tinygo-autocmpl

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: echo go test -v ./...

      - name: Publish artifact for ubuntu-latest
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.app_name }}-linux-amd64
          path: |
            ${{ env.app_name }}

      - name: Publish artifact for windows-latest
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.app_name }}-windows-amd64
          path: |
            ${{ env.app_name }}.exe

      - name: Publish artifact for macos-latest
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.app_name }}-macos-amd64
          path: |
            ${{ env.app_name }}
